apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  labels:
    visualize: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: demo-service
          servicePort: 80
